### ISSUE TITLE
[Feature Request] Add support for PLY files

### ISSUE THREAD

**Issue by ClemensU42** [GaryHuan9/Echo#29]
**Additional context**
http://paulbourke.net/dataformats/ply/

**Comment by GaryHuan9** [comment]
Follow the `.ply` specification and create a loader for the file format. Additional notes:
- The loader can be situated somewhere in the `Echo.Core.InOut` namespace.
- Note that the `.ply` has both an ASCII format and a binary format. Let us work towards the ASCII format first and place the binary format as a future goal to support larger mesh files.
- Do not worry about multithreaded loading for now.
- Do not place everything in the constructor. The constructor should only `construct` the loader, use separate methods to perform the actual loading :)
- The loaded data can be in a custom format for the loader (for now), when we integrate it with `Echo.Scenic` (through the `.echo` format) we will need to translate it into `PreparedTriangle`s.
- The `Echo.Scenic` system will support reading from streaming data. This mean that if `file.ply` has 1 million triangles, we should not load all of it into memory at one time. During preparation phase, `Echo.Scenic` will request data to be streamed from `file.ply` and progressively loaded into the prepared scene. 
- Try to see if there is a way to get/calculate the number of triangles that will be loaded. This is to better support the streaming system. If the exact number cannot be determined, we can figure out a way to find the upper approximation.

The reason that we want a new mesh loader targeting the `.ply` is to prepare for the incoming `.echo` scene file. One of the biggest features the `.echo` file will have is its ability to do lazy loading. Information is loaded at the latest point when they are needed and metadata (such as triangle count from `.ply` files) will be used to direct `PreparedScene` construction and other heuristics to better utilize multiple cores on a large scale.
