### ISSUE TITLE
[Feature Request] Add a dithering post processing layer to convert RGB128 into levels that more align with an 8 bit output channel

### ISSUE THREAD

**Issue by ClemensU42** [GaryHuan9/Echo#31]
**Describe the solution you'd like**
Use the Floyd-Steinberg dithering algorithm to better convert RGBA128 to RGBA32)

**Additional context**
https://www.youtube.com/watch?v=lseR6ZguBNY

**Comment by GaryHuan9** [comment]
Dithering is added to `SystemSerializer` as a minor feature in #18 .
