### ISSUE TITLE
[Feature Request] Optimizing and documenting the PolygonFileFormatReader

### ISSUE THREAD

**Issue by ClemensU42** [GaryHuan9/Echo#44]
**Is your feature request related to a problem? Please describe.**
Looking at the PolygonFileFormatReader, there are a lot of things that can be improved in terms of performance, readability and documentation.

**Describe the solution you'd like**
The PolygonFileFormatReader should be able to load the default blender monkey head in less than 10ms, maybe in even less time

**Comment by GaryHuan9** [comment]
Issue looks good! Yes we definitely need the optimization. Single mesh sizes are regularly in the millions of triangles range so we need to be able to load them fast.
